apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sharing-service
  template:
    metadata:
      labels:
        app: sharing-service
    spec:
      containers:
      - name: sharing-service
        image: ciphershare-sharing-service:latest
        ports:
        - containerPort: 8083
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/ciphershare
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: root
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://eureka-server:8761/eureka
---
apiVersion: v1
kind: Service
metadata:
  name: sharing-service
spec:
  selector:
    app: sharing-service
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP
