server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VedantKothari01/ciphershare-config
          search-paths: '{application}'
          default-label: main
          clone-on-start: true
          force-pull: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true 